name: Update VMware Tools Versions

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-versions:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug directory structure
        shell: pwsh
        run: |
          Write-Host "Current directory:"
          Get-Location
          Write-Host "`nDirectory contents:"
          Get-ChildItem -Recurse

      - name: Run PowerShell script
        shell: pwsh
        run: |
          # Run the script from its location
          ./GetVMwareVersions.ps1

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vmware-tools-versions.json vmware-esxi-versions.json vmware-vcenter-versions.json vmware-cloud-foundation-versions.json last-updated.json
          git status --porcelain | grep -q . && (git commit -m "Update VMware Tools versions" && git push) || echo "No changes to commit" 