name: VMware Versions Scraper

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write

jobs:
  scrape-vmware-versions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run VMware scraper
      run: |
        python vmware_tools_scraper.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add vmware-versions.json index.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Update VMware versions - $(date)"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}